#!/bin/sh
# /etc/cron.daily/backup-ceres on eurydice
# back up futel directories of interest with rsync

REMOTEDIR=/opt/asterisk
KEYFILE=/opt/futel/ssh/id_rsa
SSHCMD="ssh -i $KEYFILE -p 42422"
USER=backup
HOST=futel2.dyndns.org
DATE=`date "+%Y-%m"`
LOCALDIR=/opt/futel/backups/$DATE

rsync -avcR --delete -e "$SSHCMD" $USER@$HOST:$REMOTEDIR $LOCALDIR

